
# === Core ===
env=dev
baseUri=https://reqres.in
timeout.ms=10000
default.headers.Content-Type=application/json
default.headers.Accept=application/json
default.headers.X-Client=restassured-bdd-demo
default.headers.x-api-key=reqres_5856a1ea5b704ad1a1ca2b945a5d511b

# === Endpoints Users ===
api.users.base=/api/users
api.users.create=/api/users
api.users.byId=/api/users/{0}
api.users.update=/api/users/{0}
api.users.delete=/api/users/{0}
